In [1]:
import pandas as pd
df=pd.read_csv("car data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [2]:
x=df.iloc[:,1:]
y=df.iloc[:,0]
print(x)
print(y)

     Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0    2014           3.35           5.59       27000    Petrol      Dealer
1    2013           4.75           9.54       43000    Diesel      Dealer
2    2017           7.25           9.85        6900    Petrol      Dealer
3    2011           2.85           4.15        5200    Petrol      Dealer
4    2014           4.60           6.87       42450    Diesel      Dealer
..    ...            ...            ...         ...       ...         ...
296  2016           9.50          11.60       33988    Diesel      Dealer
297  2015           4.00           5.90       60000    Petrol      Dealer
298  2009           3.35          11.00       87934    Petrol      Dealer
299  2017          11.50          12.50        9000    Diesel      Dealer
300  2016           5.30           5.90        5464    Petrol      Dealer

    Transmission  Owner
0         Manual      0
1         Manual      0
2         Manual      0
3         Manual      0
4         Manual      0
..           ...    ...
296       Manual      0
297       Manual      0
298       Manual      0
299       Manual      0
300       Manual      0

[301 rows x 8 columns]
0         ritz
1          sx4
2         ciaz
3      wagon r
4        swift
        ...
296       city
297       brio
298       city
299       city
300       brio
Name: Car_Name, Length: 301, dtype: object

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(240, 8)
(61, 8)
(240,)
(61,)

In [4]:
import pandas as pd
df=pd.read_csv("Advertising.csv")
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [5]:
x=df.iloc[:,1:]
y=df.iloc[:,0]
print(x)
print(y)

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]
0        1
1        2
2        3
3        4
4        5
      ...
195    196
196    197
197    198
198    199
199    200
Name: Unnamed: 0, Length: 200, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [7]:
df.isna().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [8]:
df.columns

Index(['Unnamed: 0', 'TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [9]:
x=df[["TV","Radio","Newspaper"]]
y=df["Sales"]
print(x.shape)
print(y.shape)

(200, 3)
(200,)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(160, 3)
(40, 3)
(160,)
(40,)

In [11]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print(y_pred)

[21.73577184 16.45693776  7.65993185 17.89202679 18.67730671 23.86271904
 16.33623628 13.45649226  9.177296   17.36056228 14.4677995   9.85697601
 17.26057027 16.71866935 15.09530285 15.58923732 12.45188167 17.27925151
 11.0944114  18.06889853  9.33433055 12.91345761  8.7842804  10.46670654
 11.40303174 15.03104665  9.78479388 19.46028647 18.22954934 17.1958903
 21.60304218 14.71901407 16.29205532 12.36432281 19.98831261 15.37556411
 13.96678297 10.06809496 20.97197274  7.45877832]

In [12]:
diff=pd.DataFrame({"Actual":y_test,
                   "Predicted":y_pred})
diff

     Actual  Predicted
58     23.8  21.735772
40     16.6  16.456938
34      9.5   7.659932
102    14.8  17.892027
184    17.6  18.677307
198    25.5  23.862719
95     16.9  16.336236
4      12.9  13.456492
29     10.5   9.177296
168    17.1  17.360562
171    14.5  14.467799
18     11.3   9.856976
11     17.4  17.260570
89     16.7  16.718669
110    13.4  15.095303
118    15.9  15.589237
159    12.9  12.451882
35     12.8  17.279252
136     9.5  11.094411
59     18.4  18.068899
51     10.7   9.334331
16     12.5  12.913458
44      8.5   8.784280
94     11.5  10.466707
31     11.9  11.403032
162    14.9  15.031047
38     10.1   9.784794
28     18.9  19.460286
193    19.6  18.229549
27     15.9  17.195890
47     23.2  21.603042
165    11.9  14.719014
194    17.3  16.292055
177    11.7  12.364323
176    20.2  19.988313
97     15.5  15.375564
174    11.5  13.966783
73     11.0  10.068095
69     22.3  20.971973
172     7.6   7.458778

In [13]:
print("Coefficient:",lr.coef_)
print("Intercept:",lr.intercept_)

Coefficient: [0.0468431  0.17854434 0.00258619]
Intercept: 2.9079470208164295

In [14]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("MAE : ",mean_absolute_error(y_test,y_pred))
print("MSE : ",mean_squared_error(y_test,y_pred))
print("R2 Score : ",r2_score(y_test,y_pred))

MAE :  1.0402154012924718
MSE :  1.9918855518287906
R2 Score :  0.8927605914615384

In [16]:
import pandas as pd
df=pd.read_csv("FuelConsumptionCo2.csv")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [17]:
df.drop(columns=["MAKE","MODEL","VEHICLECLASS","TRANSMISSION"],axis=1,inplace=True)
df.head()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,2.0,4,Z,9.9,6.7,8.5,33,196
1,2014,2.4,4,Z,11.2,7.7,9.6,29,221
2,2014,1.5,4,Z,6.0,5.8,5.9,48,136
3,2014,3.5,6,Z,12.7,9.1,11.1,25,255
4,2014,3.5,6,Z,12.1,8.7,10.6,27,244

In [19]:
df["Age"]=2026-df["MODELYEAR"]
df

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,Age
0,2014,2.0,4,Z,9.9,6.7,8.5,33,196,12
1,2014,2.4,4,Z,11.2,7.7,9.6,29,221,12
2,2014,1.5,4,Z,6.0,5.8,5.9,48,136,12
3,2014,3.5,6,Z,12.7,9.1,11.1,25,255,12
4,2014,3.5,6,Z,12.1,8.7,10.6,27,244,12
...,...,...,...,...,...,...,...,...,...,...
1062,2014,3.0,6,X,13.4,9.8,11.8,24,271,12
1063,2014,3.2,6,X,13.2,9.5,11.5,25,264,12
1064,2014,3.0,6,X,13.4,9.8,11.8,24,271,12
1065,2014,3.2,6,X,12.9,9.3,11.3,25,260,12
1066,2014,3.2,6,X,14.9,10.2,12.8,22,294,12

In [20]:
df.drop(columns=["MODELYEAR"],inplace=True)
df

,ENGINESIZE,CYLINDERS,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,Age
0,2.0,4,Z,9.9,6.7,8.5,33,196,12
1,2.4,4,Z,11.2,7.7,9.6,29,221,12
2,1.5,4,Z,6.0,5.8,5.9,48,136,12
3,3.5,6,Z,12.7,9.1,11.1,25,255,12
4,3.5,6,Z,12.1,8.7,10.6,27,244,12
...,...,...,...,...,...,...,...,...,...
1062,3.0,6,X,13.4,9.8,11.8,24,271,12
1063,3.2,6,X,13.2,9.5,11.5,25,264,12
1064,3.0,6,X,13.4,9.8,11.8,24,271,12
1065,3.2,6,X,12.9,9.3,11.3,25,260,12
1066,3.2,6,X,14.9,10.2,12.8,22,294,12

In [22]:
df.corr(numeric_only=True)

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,Age
ENGINESIZE,1.000000,0.934011,0.832225,0.778746,0.819482,-0.808554,0.874154,NaN
CYLINDERS,0.934011,1.000000,0.796473,0.724594,0.776788,-0.770430,0.849685,NaN
FUELCONSUMPTION_CITY,0.832225,0.796473,1.000000,0.965718,0.995542,-0.935613,0.898039,NaN
FUELCONSUMPTION_HWY,0.778746,0.724594,0.965718,1.000000,0.985804,-0.893809,0.861748,NaN
FUELCONSUMPTION_COMB,0.819482,0.776788,0.995542,0.985804,1.000000,-0.927965,0.892129,NaN
FUELCONSUMPTION_COMB_MPG,-0.808554,-0.770430,-0.935613,-0.893809,-0.927965,1.000000,-0.906394,NaN
CO2EMISSIONS,0.874154,0.849685,0.898039,0.861748,0.892129,-0.906394,1.000000,NaN
Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
x=df[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_COMB"]]
y=df["CO2EMISSIONS"]
print(x.shape)
print(y.shape)

(1067, 3)
(1067,)

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(853, 3)
(214, 3)
(853,)
(214,)