In [1]:
import requests,json
def current_weather():
    api_key="75b80d48c71af37eb15d22e0d0250469"
    city=input("Enter the City name: ")
    request_url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}"
    response=requests.get(request_url)
    coordinates=response.json()
    lat=coordinates[0]["lat"]
    lon=coordinates[0]["lon"]
    request_url1=f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"
    response1=requests.get(request_url1)
    weather_data=response1.json();
    print(json.dumps(weather_data,indent=5))
    des=weather_data["weather"][0]["description"]
    temp=weather_data["main"]["temp"]
    press=weather_data["main"]["pressure"]
    hum=weather_data["main"]["humidity"]
    vis=weather_data["visibility"]
    win_sp=weather_data["wind"]["speed"]
    print("====================")
    print("Current Weather data of current city :",city);
    print("--------------------")
    print("Weather Description :",des)
    print("Temperature :",temp)
    print("Pressure :",press)
    print("Humidity :",hum)
    print("Visibility :",vis)
    print("Wind Speed :",win_sp)
current_weather()

Enter the City name:  Ahmedabad

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "weather": [
          {
               "id": 721,
               "main": "Haze",
               "description": "haze",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 303.19,
          "feels_like": 305.66,
          "temp_min": 303.19,
          "temp_max": 303.19,
          "pressure": 1009,
          "humidity": 58,
          "sea_level": 1009,
          "grnd_level": 1004
     },
     "visibility": 3000,
     "wind": {
          "speed": 3.6,
          "deg": 200
     },
     "clouds": {
          "all": 40
     },
     "dt": 1779769400,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779755113,
          "sunset": 1779803309
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}
====================
Current Weather data of current city : Ahmedabad
--------------------
Weather Description : haze
Temperature : 303.19
Pressure : 1009
Humidity : 58
Visibility : 3000
Wind Speed : 3.6

In [2]:
import requests
def Air_pollution():
    api_key="75b80d48c71af37eb15d22e0d0250469"
    city=input("Enter the City name: ")
    request_url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}"
    response=requests.get(request_url)
    coordinates=response.json()
    lat=coordinates[0]["lat"]
    lon=coordinates[0]["lon"]
    request_url1=f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={api_key}"
    response1=requests.get(request_url1)
    air_pollution=response1.json();
    air=air_pollution["list"][0]["main"]["aqi"]
    print(json.dumps(air_pollution,indent=5))
    print(f"The index for the {city} city is: ",air)
Air_pollution()

Enter the City name:  Ahmedabad

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "list": [
          {
               "main": {
                    "aqi": 2
               },
               "components": {
                    "co": 104.36,
                    "no": 0.48,
                    "no2": 1.53,
                    "o3": 40.76,
                    "so2": 2,
                    "pm2_5": 8.45,
                    "pm10": 29.1,
                    "nh3": 1.02
               },
               "dt": 1779769566
          }
     ]
}
The index for the Ahmedabad city is:  2

In [3]:
import requests
def five_day_forecast():
    api_key="75b80d48c71af37eb15d22e0d0250469"
    city=input("Enter the City name: ")
    request_url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}"
    response=requests.get(request_url)
    coordinates=response.json()
    lat=coordinates[0]["lat"]
    lon=coordinates[0]["lon"]
    request_url1=f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}"
    response1=requests.get(request_url1)
    five_day=response1.json();
    return five_day
five_day=five_day_forecast()

Enter the City name:  Ahmedabad

In [4]:
import pandas as pd
data={"Date_Time":[],"Description":[],"Temp":[],"Pressure":[],"Humidity":[],"Visibility":[],"Wind Speed":[]}
for i in five_day["list"]:
    data["Date_Time"].append(i["dt_txt"])
    data["Description"].append(i["weather"][0]["description"])
    data["Temp"].append(i["main"]["temp"])
    data["Pressure"].append(i["main"]["pressure"])
    data["Humidity"].append(i["main"]["humidity"])
    data["Visibility"].append(i["visibility"]) 
    data["Wind Speed"].append(i["wind"]["speed"])
df=pd.DataFrame(data)
df

,Date_Time,Description,Temp,Pressure,Humidity,Visibility,Wind Speed
0,2026-05-26 06:00:00,scattered clouds,305.84,1009,48,10000,4.81
1,2026-05-26 09:00:00,few clouds,311.48,1006,30,10000,4.97
2,2026-05-26 12:00:00,clear sky,316.02,1003,15,10000,5.57
3,2026-05-26 15:00:00,clear sky,308.33,1006,40,10000,5.07
4,2026-05-26 18:00:00,clear sky,305.23,1007,56,10000,3.28
5,2026-05-26 21:00:00,clear sky,303.04,1006,63,10000,3.99
6,2026-05-27 00:00:00,clear sky,302.61,1007,62,10000,4.69
7,2026-05-27 03:00:00,clear sky,304.92,1009,51,10000,4.88
8,2026-05-27 06:00:00,clear sky,311.75,1008,25,10000,5.26
9,2026-05-27 09:00:00,clear sky,316.06,1005,15,10000,5.55
10,2026-05-27 12:00:00,clear sky,316.54,1003,14,10000,5.76
11,2026-05-27 15:00:00,clear sky,306.63,1006,52,10000,5.80
12,2026-05-27 18:00:00,clear sky,305.25,1008,53,10000,3.26
13,2026-05-27 21:00:00,clear sky,302.86,1007,65,10000,4.76
14,2026-05-28 00:00:00,clear sky,302.99,1007,59,10000,5.46
15,2026-05-28 03:00:00,clear sky,304.97,1009,52,10000,5.78
16,2026-05-28 06:00:00,clear sky,312.29,1007,24,10000,6.10
17,2026-05-28 09:00:00,clear sky,317.47,1004,12,10000,6.34
18,2026-05-28 12:00:00,clear sky,317.16,1002,14,10000,5.57
19,2026-05-28 15:00:00,clear sky,307.22,1006,48,10000,5.11
20,2026-05-28 18:00:00,clear sky,305.02,1006,47,10000,4.12
21,2026-05-28 21:00:00,clear sky,304.29,1006,53,10000,5.49
22,2026-05-29 00:00:00,clear sky,302.32,1007,65,10000,5.30
23,2026-05-29 03:00:00,clear sky,304.90,1008,53,10000,7.29
24,2026-05-29 06:00:00,clear sky,311.96,1007,25,10000,7.93
25,2026-05-29 09:00:00,clear sky,316.01,1003,17,10000,8.26
26,2026-05-29 12:00:00,clear sky,315.72,1001,18,10000,8.02
27,2026-05-29 15:00:00,clear sky,307.52,1003,38,10000,8.54
28,2026-05-29 18:00:00,clear sky,306.29,1003,43,10000,5.63
29,2026-05-29 21:00:00,clear sky,303.51,1003,56,10000,5.95
30,2026-05-30 00:00:00,clear sky,302.12,1004,67,10000,6.76
31,2026-05-30 03:00:00,clear sky,304.78,1005,55,10000,8.50
32,2026-05-30 06:00:00,clear sky,311.35,1003,31,10000,8.74
33,2026-05-30 09:00:00,clear sky,315.53,1000,21,10000,8.96
34,2026-05-30 12:00:00,clear sky,314.44,999,23,10000,8.54
35,2026-05-30 15:00:00,clear sky,309.75,1001,35,10000,7.15
36,2026-05-30 18:00:00,clear sky,305.37,1003,52,10000,7.87
37,2026-05-30 21:00:00,clear sky,303.05,1003,66,10000,5.38
38,2026-05-31 00:00:00,clear sky,302.22,1003,70,10000,5.18
39,2026-05-31 03:00:00,scattered clouds,304.36,1005,59,10000,7.10

In [8]:
nasa_api="t5PrfRBZwcGRfYMm6tgp10rBJ21n6nE2REknYGH1"

In [6]:
import requests
url="http://api.nasa.gov/planetary/apod"
response=requests.get(url,params={"api_key":"t5PrfRBZwcGRfYMm6tgp10rBJ21n6nE2REknYGH1","date":"2026-05-26"})
data=response.json()
print(data["url"])

https://apod.nasa.gov/apod/image/2605/Ngc3660Burcin_Block_960.jpg

In [14]:
import pandas as pd
import requests
url="http://api.nasa.gov/planetary/apod"
response=requests.get(url,params={"api_key":"t5PrfRBZwcGRfYMm6tgp10rBJ21n6nE2REknYGH1","count":10})
data=response.json()
date=[]
url=[]
for i in data:
    date.append(i["date"])
    url.append(i["url"])
df=pd.DataFrame({"Date":date,"URLs":url})
df

         Date                                               URLs
0  1996-04-06  https://apod.nasa.gov/apod/image/andromeda_neb...
1  2025-06-22  https://apod.nasa.gov/apod/image/2506/berrybow...
2  2020-06-06  https://apod.nasa.gov/apod/image/2006/C2017T2_...
3  2020-07-05  https://apod.nasa.gov/apod/image/2007/NorthSat...
4  2011-02-20  https://apod.nasa.gov/apod/image/1102/mammatus...
5  2019-04-20  https://apod.nasa.gov/apod/image/1904/SpaceXFa...
6  2022-11-16  https://apod.nasa.gov/apod/image/2211/NGC-1097...
7  2014-12-19  https://apod.nasa.gov/apod/image/1412/LRGBv2-X...
8  2008-10-17  https://apod.nasa.gov/apod/image/0810/ATVreent...
9  2023-12-15  https://apod.nasa.gov/apod/image/2312/OrionBet...